import array
import requests
import oracledb
from fastapi import FastAPI, HTTPException

app = FastAPI(title="Local Enterprise RAG Engine")

def get_db_connection():
    """Generates a direct Thin-mode database connection to the pluggable instance container"""
    return oracledb.connect(
        user="vector_dev",
        password="DevPass2026",
        dsn="localhost:1521/FREEPDB1"
    )

def generate_embedding(text: str) -> list:
    """Interfaces with local Ollama pipeline node to map strings to 768 float metrics"""
    url = "http://localhost:11434/api/embeddings"
    try:
        response = requests.post(url, json={"model": "nomic-embed-text", "prompt": text})
        response.raise_for_status()
        return response.json()["embedding"]
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ollama embedding fault: {str(e)}")

def generate_llm_response(query: str, context: str) -> str:
    """Passes the retrieved database context and user query to local TinyLlama for synthesis"""
    url = "http://localhost:11434/api/generate"
    prompt = f"""
    You are an expert enterprise assistant. Answer the user question accurately using ONLY the context provided below. 
    If the context does not contain the answer, state that you do not have that information in your database. Keep it concise.

    Context:
    {context}

    Question: {query}
    Answer:
    """
    try:
        response = requests.post(url, json={
            "model": "tinyllama",
            "prompt": prompt,
            "stream": False
        })
        response.raise_for_status()
        return response.json()["response"]
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ollama LLM generation fault: {str(e)}")

@app.on_event("startup")
def bootstrap_storage_schema():
    """Builds structural vector storage constraints natively on database startup phase"""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE enterprise_knowledge_base (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    text_chunk CLOB,
                    vector_data VECTOR(768, FLOAT32)
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)
        conn.commit()
    finally:
        cursor.close()
        conn.close()

@app.post("/ingest")
def ingest_text_node(content: str):
    """Processes content payload, generates embedding indices, and pushes straight to database"""
    if not content.strip():
        raise HTTPException(status_code=400, detail="Content block cannot be vacant")
        
    raw_floats = generate_embedding(content)
    vector_binary_binding = array.array("f", raw_floats)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "INSERT INTO enterprise_knowledge_base (text_chunk, vector_data) VALUES (:1, :2)",
            [content, vector_binary_binding]
        )
        conn.commit()
        return {"status": "Ingestion successful", "matrix_dimensions": len(raw_floats)}
    finally:
        cursor.close()
        conn.close()

@app.post("/reset")
def clear_knowledge_base():
    """Truncates the vector storage table to completely purge context and allow fresh dataset mapping"""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("TRUNCATE TABLE enterprise_knowledge_base")
        conn.commit()
        return {"status": "Database tablespace truncated successfully. System reset complete."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database maintenance fault: {str(e)}")

@app.get("/query_rag")
def comprehensive_rag_search(query: str, limit: int = 3):
    """Executes vector search over Oracle 23ai and feeds results to TinyLlama to generate an answer"""
    if not query.strip():
        raise HTTPException(status_code=400, detail="Query string cannot be vacant")
        
    query_floats = generate_embedding(query)
    query_binary_binding = array.array("f", query_floats)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT text_chunk, vector_distance(vector_data, :1, COSINE) as distance 
            FROM enterprise_knowledge_base 
            ORDER BY distance ASC
            FETCH FIRST :2 ROWS ONLY
        """, [query_binary_binding, limit])
        
        fetched_rows = cursor.fetchall()
        if not fetched_rows:
            return {"query": query, "ai_response": "No matching context found in the database.", "matches": []}
            
        context_chunks = []
        matches_data = []
        
        for row in fetched_rows:
            db_lob_stream = row[0]
            text_string = db_lob_stream.read() if hasattr(db_lob_stream, "read") else db_lob_stream
            cosine_dist = float(row[1])
            
            context_chunks.append(text_string)
            matches_data.append({
                "chunk": text_string,
                "cosine_distance": cosine_dist
            })
            
        combined_context = "\n---\n".join(context_chunks)
        ai_answer = generate_llm_response(query, combined_context)
        
        return {
            "query": query,
            "ai_response": ai_answer,
            "matches": matches_data
        }
    finally:
        cursor.close()
        conn.close()